import { useMemo, useState } from "react";
import { CreditCard, Loader2, RefreshCw, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useListFees } from "@/lib/hooks";

type Fee = { id: string; studentName?: string; month?: string; amount: number; status?: string; installments?: { amount: number; paidAt: string; note?: string; collectedBy?: string }[]; paidAt?: string | null };
type Payment = { id: string; feeId: string; studentName: string; amount: number; paidAt: string; note: string; collectedBy: string; month: string };

export default function PaymentHistory() {
  const query = useListFees();
  const [search, setSearch] = useState("");
  const payments = useMemo(() => (query.data as Fee[] ?? []).flatMap((fee) => {
    const installments = fee.installments?.length ? fee.installments : fee.status === "paid" ? [{ amount: fee.amount, paidAt: fee.paidAt || "", note: "Full payment", collectedBy: "Recorded payment" }] : [];
    return installments.map((item, index) => ({ id: `${fee.id}-${index}`, feeId: fee.id, studentName: fee.studentName || "Unnamed student", amount: Number(item.amount), paidAt: item.paidAt, note: item.note || "Payment", collectedBy: item.collectedBy || "Administrative staff", month: fee.month || "—" }));
  }).filter((payment) => !search || payment.studentName.toLowerCase().includes(search.toLowerCase()) || payment.note.toLowerCase().includes(search.toLowerCase())).sort((a, b) => new Date(b.paidAt).getTime() - new Date(a.paidAt).getTime()), [query.data, search]);
  const total = payments.reduce((sum, payment) => sum + payment.amount, 0);
  return <div className="app-command-surface mx-auto max-w-7xl space-y-6 pb-12"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Administrative workspace</p><h1 className="mt-2 font-display text-3xl tracking-tight sm:text-4xl">Payment History</h1><p className="mt-1 text-sm text-muted-foreground">A complete, searchable history of collected installments and fee payments.</p></div><Button variant="outline" className="w-fit gap-2" onClick={() => query.refetch()} disabled={query.isFetching}><RefreshCw className={query.isFetching ? "h-4 w-4 animate-spin" : "h-4 w-4"} />Refresh</Button></header><div className="grid gap-4 sm:grid-cols-3"><Metric label="Payments recorded" value={payments.length} /><Metric label="Collected total" value={`৳${total.toLocaleString("en-BD")}`} tone="emerald" /><Metric label="Latest month" value={payments[0]?.month || "—"} tone="amber" /></div><Card className="overflow-hidden border-border/70 bg-card/70 backdrop-blur-xl"><CardHeader className="border-b border-border/60"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><CardTitle className="text-lg">Collected payments</CardTitle><div className="relative sm:w-72"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search history..." className="pl-9" aria-label="Search payment history" /></div></div></CardHeader><CardContent className="p-0">{query.isLoading ? <div className="flex min-h-56 items-center justify-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />Loading payment history...</div> : payments.length === 0 ? <div className="flex min-h-56 items-center justify-center text-sm text-muted-foreground">No payments have been recorded yet.</div> : <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Month</TableHead><TableHead>Payment date</TableHead><TableHead>Note</TableHead><TableHead>Collected by</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader><TableBody>{payments.map((payment) => <TableRow key={payment.id}><TableCell className="font-medium">{payment.studentName}</TableCell><TableCell>{payment.month}</TableCell><TableCell className="whitespace-nowrap">{payment.paidAt ? new Date(payment.paidAt).toLocaleDateString("en-BD", { day: "2-digit", month: "short", year: "numeric" }) : "—"}</TableCell><TableCell><Badge variant="outline">{payment.note}</Badge></TableCell><TableCell className="text-muted-foreground">{payment.collectedBy}</TableCell><TableCell className="text-right font-semibold text-emerald-600">৳{payment.amount.toLocaleString("en-BD")}</TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card></div>;
}
function Metric({ label, value, tone = "violet" }: { label: string; value: string | number; tone?: "violet" | "amber" | "emerald" }) { const colors = { violet: "text-primary bg-primary/10", amber: "text-amber-600 bg-amber-500/10", emerald: "text-emerald-600 bg-emerald-500/10" }; return <Card className="border-border/70 bg-card/70"><CardContent className="p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div><CreditCard className={`h-5 w-5 rounded-md p-0.5 ${colors[tone]}`} /></div></CardContent></Card>; }