// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/edutrack-setup-wizard/SetupComplete.tsx": () => import("../components/mockups/edutrack-setup-wizard/SetupComplete.tsx")
};
