// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pricing-cards/CinematicDark.tsx": () => import("../components/mockups/pricing-cards/CinematicDark.tsx"),
  "./components/mockups/pricing-cards/GoldFocal.tsx": () => import("../components/mockups/pricing-cards/GoldFocal.tsx"),
  "./components/mockups/pricing-cards/NeonPurple.tsx": () => import("../components/mockups/pricing-cards/NeonPurple.tsx")
};
